includeConfigs:
  - ${GEN3_WORKFLOW_DIR}/python/desc/gen3_workflow/etc/bps_drp_baseline.yaml
  - ${HOME}/BOT_gen3_testing/bps_cp_pipe_resource_info.yaml
  - ${PWD}/bps_parsl_config.yaml

operator: jchiang
pipelineYaml: "pipelines/cpPhotodiodeCorrection.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  bot_run: 13162
  weekly: w_2022_34
  inCollection: u/jchiang/linearitySolve_{bot_run}_{weekly}
  payloadName: photodiodeCorrection_{bot_run}_{weekly}
  butlerConfig: /sdf/group/lsst/camera/IandT/repo_gen3/BOT_data
  dataQuery: "instrument='LSSTCam' and exposure.science_program='{bot_run}' and exposure.observation_type='flat' and exposure.observation_reason='flat' and exposure=3021121200360"
