includeConfigs:
  - ${CP_PIPE_PROCESSING_DIR}/config/bps/bps_default_configs.yaml

extraQgraphOptions: "{isr_QgraphOptions} --config isr:doDefect=False"

operator: jchiang
pipelineYaml: "${CP_PIPE_DIR}/pipelines/cpBias.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  b_protocol_run: 13162
  weekly: w_2022_34
  inCollection: LSSTCam/raw/all,LSSTCam/calib
  payloadName: bias_0_{b_protocol_run}_{weekly}
  butlerConfig: ${BUTLER_CONFIG}
  dataQuery: "instrument='LSSTCam' and exposure.science_program='{b_protocol_run}' and exposure.observation_type='bias' and exposure.observation_reason='bias'"
