includeConfigs:
  - ${CP_PIPE_PROCESSING_DIR}/config/bps/bps_default_configs.yaml

operator: jchiang
pipelineYaml: "${CP_PIPE_PROCESSING_DIR}/pipelines/cpPtc_0.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  b_protocol_run: 13162
  bot_run: 13144
  weekly: w_2022_34
  inCollection: u/jchiang/flat_0_{b_protocol_run}_{weekly}
  payloadName: ptc_0_{bot_run}_{weekly}
  butlerConfig: ${BUTLER_CONFIG}
  dataQuery: "instrument='LSSTCam' and exposure.science_program='{bot_run}' and exposure.observation_type='flat' and exposure.observation_reason='flat'"
