includeConfigs:
  - ${CP_PIPE_PROCESSING_DIR}/config/bps/bps_default_configs.yaml

operator: jchiang
pipelineYaml: "${CP_PIPE_PROCESSING_DIR}/pipelines/cpBfkSolve.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  bot_run: 13162
  weekly: w_2022_34
  inCollection: u/jchiang/ptc_{bot_run}_{weekly}
  payloadName: bfkSolve_{bot_run}_{weekly}
  butlerConfig: ${BUTLER_CONFIG}
  dataQuery: "instrument='LSSTCam' and exposure.science_program='{bot_run}'and exposure.observation_type='flat' and exposure.observation_reason='flat' and exposure=3021121200360"
