includeConfigs:
  - ${CP_PIPE_PROCESSING_DIR}/config/bps/bps_default_configs.yaml

extraQgraphOptions: "{isr_QgraphOptions} --config isr:doLinearize=True --config isr:doCrosstalk=False"

pipelineYaml: "${CP_PIPE_DIR}/pipelines/cpPtc.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  ptc_run: 13144
  b_protocol_run: 13162
  weekly: ${WEEKLY}
  inCollection: u/{operator}/flat_{b_protocol_run}_{weekly}
  payloadName: ptc_{ptc_run}_{weekly}
  butlerConfig: ${BUTLER_CONFIG}
  dataQuery: "instrument='LSSTCam' and exposure.science_program='{ptc_run}' and exposure.observation_type='flat' and exposure.observation_reason='flat'"
