includeConfigs:
  - ${CP_PIPE_PROCESSING_DIR}/config/bps/bps_default_configs.yaml

operator: jchiang
pipelineYaml: "${CP_PIPE_DIR}/pipelines/cpBfkSolve.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  ptc_run: 13144
  template_exposure: 3021121200360
  weekly: w_2022_34
  inCollection: u/{operator}/ptc_{ptc_run}_{weekly}
  payloadName: bfkSolve_{ptc_run}_{weekly}
  butlerConfig: ${BUTLER_CONFIG}
  dataQuery: "instrument='LSSTCam' and exposure={template_exposure}"
