includeConfigs:
  - ${CP_PIPE_PROCESSING_DIR}/config/bps/bps_default_configs.yaml

operator: jchiang
pipelineYaml: "${CP_PIPE_PROCESSING_DIR}/pipelines/cpLinearityCorrected.yaml"
instrument: lsst.obs.lsst.LsstCam

payload:
  bot_run: 13144
  weekly: w_2022_34
  inCollection: u/jchiang/ptc_0_{bot_run}_{weekly}
  payloadName: linearityCorrected_{bot_run}_{weekly}
  butlerConfig: ${BUTLER_CONFIG}
  dataQuery: "instrument='LSSTCam' and exposure.science_program='{bot_run}'"
#  and exposure=3021120600654"
